version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - OMDB_API_KEY=${OMDB_API_KEY}
      - REDIS_URL=redis
      - NODE_ENV=production
    depends_on:
      - redis
    links:
      - redis
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://server:8080
      - NODE_ENV=production
    depends_on:
      - server
    links:
      - server
