FROM node:18-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --no-cache

# Copy app files
COPY . .

# Build the application for production
RUN npm run build

# Remove development dependencies
RUN npm prune --production

# Remove unnecessary files
RUN rm -rf \
  src/ \
  .env \
  .gitignore \
  .nodemon.json \
  tsconfig.json \
  package*.json

EXPOSE 8080

CMD ["node", "dist/index.js"]